### ISSUE TITLE
Use http proxy to strip the PNG header

### ISSUE THREAD

**Issue by larvata** [D4anielCB/plugin.video.Cinput#1]
Hi, I have read your post:
https://github.com/xbmc/inputstream.ffmpegdirect/issues/100

I'm working on a similar addon and stuck on the PNG header too.
I think the kodi service addon seems can work around this problem,
run a reverse proxy as kodi service for striping the PNG header, and modify the HLS playlist to request the video chunks from this reverse proxy.

I haven't tried it yet, do you think this will work?

**Comment by larvata** [comment]
I wrote the reverse proxy service, it works

```python
import xbmc
from http.server import BaseHTTPRequestHandler, HTTPServer
from urllib.parse import parse_qsl, urlparse
import requests
import threading


class ProxyHTTPRequestHandler(BaseHTTPRequestHandler):
    protocol_version = 'HTTP/1.0'

    def do_GET(self):
        p = urlparse(self.path)
        q = dict(parse_qsl(p.query))

        if 'u' not in q:
            self.send_error(404)
            return

        u = q['u']
        url = u[:-3] if u.endswith('-no') else u
        print(url)
        res = requests.get(url)
        ret = res.content[8:]
        self.send_header('Content-Length', len(ret))
        self.send_header('Content-Type', 'video/MP2T')
        self.end_headers()
        self.wfile.write(ret)


if __name__ == '__main__':
    server_address = ('127.0.0.1', 8964)
    httpd = HTTPServer(server_address, ProxyHTTPRequestHandler)
    print('http server is running')
    # httpd.serve_forever()

    server_thread = threading.Thread(target=httpd.serve_forever)
    server_thread.start()

    monitor = xbmc.Monitor()

    while not monitor.waitForAbort(3):
        pass

    httpd.shutdown()
    server_thread.join()
```

**Comment by sviet2k** [comment]
Hi @larvata 

Thanks a lot for solution.
But I don't know how to call this proxy from the client.
Here is the url I would like to pass to proxy:
hxxp://biphim.club/hls/596ae1c149b1b9a364777486fb46112b/596ae1c149b1b9a364777486fb46112b?v=1616010660

I tried to call proxy with the following one, but it failed.
hxxp://127.0.0.1:8964?hxxp://biphim.club/hls/596ae1c149b1b9a364777486fb46112b/596ae1c149b1b9a364777486fb46112b?v=1616010660

Thanks in advance for your help.

**Comment by larvata** [comment]
```python
segment_url = 'hxxp://biphim.club/hls/596ae1c149b1b9a364777486fb46112b/596ae1c149b1b9a364777486fb46112b?v=1616010660'
final_url = 'hxxp://127.0.0.1:8964?u=' + urllib.parse.quote(segment_url)
```

**Comment by sviet2k** [comment]
Thanks a lot for your help @larvata.
It's working. :)
Because my url   is a m3u8, I change the content-type to 'application/vnd.apple.mpegurl'
And I add this line:
res = res.replace('hxxps://facebookstream.club','hxxp://127.0.0.1:5059?u=hxxs://facebookstream.club')
to continue to send the facebook link to proxy.

Again thanks a lot for your help.

**Comment by D4anielCB** [comment]
@larvata I dont know why i didnt see that answer, im sorry. Thank you very much for your answer, ill check that
